// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuzcoefsvmxomnvfvpzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1emNvZWZzdm14b21udmZ2cHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2ODgzNzEsImV4cCI6MjA4NzI2NDM3MX0.LSD_fYMYnXaPmvI77RDF17qysvM1vKlezMnrOZvTUys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});